### ISSUE TITLE
MVP Review

### ISSUE THREAD

**Issue by danemauland** [hollyjphilly/YourTube#1]
Hey Holly, great work with your MVPs! I just have a few relatively minor pieces of feedback:

-Add projected completion dates
 New account creation:
 -The second bullet point is a direct copy-paste from the bluebird sample. It needs to be reworded.
 -Which features require users to be logged in? You mention in the other MVPs whether or not the user needs to be logged in for that feature, but state it here, too.
Videos
-Your video playback will be a large part of the user experience. What functionality will it have (e.g. 10 secord rewind, volume control, etc).
 Subscribe
 -Consider moving this to a bonus feature--It's a great feature that should be in your polished end-product, but the other features are enough to focus on for these first two weeks.

**Comment by hollyjphilly** [comment]
-Added projected completion dates

New account creation:
-Reworded second bullet point, thought Val said those would be the same for everyone so didn't think it needed to be
-Added which features require users to be logged in

Videos
-Still uncertain what video playback functionality I will have. MVP functionality would be play, pause, and draggable time marker.

Subscribe
-Moved this to a bonus feature.
