### ISSUE TITLE
Schema Review

### ISSUE THREAD

**Issue by danemauland** [hollyjphilly/YourTube#2]
Great work on your schema! There are only some minor issues/revisions:

-Review your uniqueness constraints and what you have indexed. For example, why con't you have two users with the same first name? Why is first name indexed? I imagine searches for other users would be based on username
-Add indices as bullet points beneath the respective tables
-As a bullet point, list which table each foreign key references, as well as the type of relationship
Comment likes/video likes
-Create these as polymorphic associations

**Comment by hollyjphilly** [comment]
-Fixed accidental uniqueness constraints, leaving indexing though I know it increases O(n) time in certain instances
-Added associations & polymorphic associations
