### ISSUE TITLE
Frontend Routes Review

### ISSUE THREAD

**Issue by danemauland** [hollyjphilly/YourTube#5]
Holly, phenomenal work on your frontend routes and components. The ability to create your outline with this level of detail requires the ability to reason through the React structure in the abstract, which in turn requires a solid intuitive understanding of React, which is atypical for students going into the fullstack projects. I'm excited to see the pay off from all your hard work during the course. I have only a couple minor revisions:

-By convention, your watch route should use a wildcard instead of a query string
-For now, consider your /account page to just display the user information. Your MVPs don't mention editing user information and you don't have a backend route dedicated to it. This would make more sense as a bonus feature than as part of your MVP.

**Comment by hollyjphilly** [comment]
-Updated watch route to use wildcard instead of query string
-Switched editing account information to bonus feature
